# Generated by Django 5.1.2 on 2024-10-20 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_education'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='univesity',
        ),
        migrations.AddField(
            model_name='education',
            name='university',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='education',
            name='field_study',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='education',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
