# Generated by Django 5.1.2 on 2024-10-25 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_file',
            field=models.FileField(default='articles/default.pdf', upload_to='articles/%Y/%m/%d/'),
        ),
    ]
