# Generated by Django 5.1.2 on 2024-10-25 21:46

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_article_article_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=django_jalali.db.models.jDateField(blank=True, null=True),
        ),
    ]
