# Generated by Django 5.1.2 on 2024-10-27 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_article_defense_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='photos/default.png', upload_to='photos/%Y/%m/%d/'),
        ),
    ]
