# Generated by Django 5.1.2 on 2024-10-27 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='other',
            field=models.FileField(default='articles/default.pdf', upload_to='articles/%Y/%m/%d/'),
        ),
    ]
