# Generated by Django 5.1.2 on 2024-10-27 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_article_other'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='accept',
            field=models.FileField(default='articles/default.pdf', upload_to='articles/%Y/%m/%d/'),
        ),
    ]
