# Generated by Django 5.1.2 on 2024-10-31 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_article_accept'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='type',
        ),
    ]
