# Generated by Django 5.1.2 on 2024-11-22 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_remove_article_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('UPL', 'Uploaded'), ('REV', 'Review'), ('ACC', 'Accepted')], default='UPL', max_length=3),
        ),
    ]
