# Generated by Django 5.1.2 on 2024-12-10 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_alter_education_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_score',
            field=models.FloatField(),
        ),
    ]
