# Generated by Django 5.1.2 on 2024-12-20 12:10

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_alter_article_options_alter_profile_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['-created'], 'verbose_name': 'سابقه تحصیلی', 'verbose_name_plural': 'سوابق تحصیلی'},
        ),
        migrations.AlterField(
            model_name='article',
            name='Requester',
            field=models.CharField(max_length=120, verbose_name='درخواست دهنده'),
        ),
        migrations.AlterField(
            model_name='article',
            name='Requester_loc',
            field=models.CharField(max_length=120, verbose_name='آدرس درخواست دهنده'),
        ),
        migrations.AlterField(
            model_name='article',
            name='accept',
            field=models.FileField(default='articles/default.pdf', upload_to='articles/%Y/%m/%d/', verbose_name='تاییدیه'),
        ),
        migrations.AlterField(
            model_name='article',
            name='adviser',
            field=models.CharField(max_length=120, verbose_name='راهنما'),
        ),
        migrations.AlterField(
            model_name='article',
            name='adviser_email',
            field=models.CharField(max_length=120, verbose_name='ایمیل راهنما'),
        ),
        migrations.AlterField(
            model_name='article',
            name='adviser_mobile',
            field=models.CharField(max_length=11, verbose_name='موبایل راهنما'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_file',
            field=models.FileField(default='articles/default.pdf', upload_to='articles/%Y/%m/%d/', verbose_name='فایل مقاله'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_score',
            field=models.FloatField(verbose_name='نمره مقاله'),
        ),
        migrations.AlterField(
            model_name='article',
            name='defense_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ دفاع'),
        ),
        migrations.AlterField(
            model_name='article',
            name='education_group',
            field=models.CharField(max_length=64, verbose_name='گروه آموزشی'),
        ),
        migrations.AlterField(
            model_name='article',
            name='other',
            field=models.FileField(default='articles/default.pdf', upload_to='articles/%Y/%m/%d/', verbose_name='دیگر'),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('UPL', 'Uploaded'), ('REV', 'Review'), ('ACC', 'Accepted')], default='UPL', max_length=3, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='article',
            name='summary',
            field=models.TextField(verbose_name='چکیده'),
        ),
        migrations.AlterField(
            model_name='article',
            name='teacher',
            field=models.CharField(max_length=120, verbose_name='استاد'),
        ),
        migrations.AlterField(
            model_name='article',
            name='teacher_email',
            field=models.CharField(max_length=120, verbose_name='ایمیل استاد'),
        ),
        migrations.AlterField(
            model_name='article',
            name='teacher_mobile',
            field=models.CharField(max_length=11, verbose_name='موبایل استاد'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=255, verbose_name='عنوان رساله'),
        ),
        migrations.AlterField(
            model_name='article',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_articles', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(max_length=120, verbose_name='مقطع تحصیلی'),
        ),
        migrations.AlterField(
            model_name='education',
            name='field_study',
            field=models.CharField(blank=True, max_length=120, verbose_name='رشته تحصیلی'),
        ),
        migrations.AlterField(
            model_name='education',
            name='score',
            field=models.FloatField(default=0, verbose_name='معدل'),
        ),
        migrations.AlterField(
            model_name='education',
            name='university',
            field=models.CharField(blank=True, max_length=120, verbose_name='دانشگاه'),
        ),
        migrations.AlterField(
            model_name='education',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city_of_birth',
            field=models.CharField(max_length=120, verbose_name='محل تولد'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ تولد'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mobile_number',
            field=models.CharField(max_length=11, verbose_name='موبایل'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='national_id',
            field=models.CharField(max_length=10, verbose_name='کد ملی'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='photos/default.png', upload_to='photos/%Y/%m/%d/', verbose_name='عکس'),
        ),
    ]
