# Generated by Django 5.1.2 on 2024-12-22 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_alter_education_options_alter_article_requester_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('UPL', 'Uploaded'), ('REV', 'Review'), ('EVA', 'Evaluation'), ('ACC', 'Accepted')], default='UPL', max_length=3, verbose_name='وضعیت'),
        ),
        migrations.CreateModel(
            name='judgement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.article', verbose_name='رساله')),
                ('referee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='داور')),
            ],
            options={
                'verbose_name': 'داوری',
                'verbose_name_plural': 'داوری ها',
                'ordering': ['-created'],
            },
        ),
    ]
