# Generated by Django 5.1.2 on 2024-12-26 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_alter_article_status_judgement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان کاربرگ')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'کاربرگ داوری',
                'verbose_name_plural': 'کاربرگ های',
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='type',
            field=models.CharField(choices=[('شرکت کننده', 'Participant'), ('سرداور', 'Chief'), ('داور', 'Referee')], default='شرکت کننده', max_length=32, verbose_name='نوع حساب کاربری'),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='سوال')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.quiz')),
            ],
            options={
                'verbose_name': 'سوال',
                'verbose_name_plural': 'سوالات',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='پاسخ')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.article', verbose_name='رساله')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.question', verbose_name='سوال')),
            ],
            options={
                'verbose_name': 'پاسخ',
                'verbose_name_plural': 'پاسخنامه',
                'ordering': ['-created'],
            },
        ),
    ]
