# Generated by Django 5.1.2 on 2024-12-28 19:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0026_remove_question_quiz_remove_response_question_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizFirst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quest_1', models.PositiveIntegerField()),
                ('quest_2', models.PositiveIntegerField()),
                ('quest_3', models.PositiveIntegerField()),
                ('quest_4', models.PositiveIntegerField()),
                ('quest_5', models.PositiveIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.article')),
                ('assistant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'پرسشنامه یک',
                'verbose_name_plural': 'پرسشنامه های یک',
                'ordering': ['-created'],
            },
        ),
    ]
