# Generated by Django 5.1.2 on 2024-12-28 20:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0027_quizfirst'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuizFirst',
            new_name='Quiz',
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['-created'], 'verbose_name': 'پرسشنامه', 'verbose_name_plural': 'پرسشنامه ها'},
        ),
    ]
